{
 "title": "Service info",
 "description": "서비스 상세 정보 대시보드",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "\n### ↓ 글로벌 지표\n---\n" }, "content": "\n### ↓ 글로벌 지표\n---\n" },
  {
   "title": "Global Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"destination\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{reporter=\"destination\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"4.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"5.*\"}[1m])) "
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 }, "options": { "content": "\n### ↓ prod 서비스 지표\n---" }, "content": "\n### ↓ prod 서비스 지표\n---" },
  {
   "title": "rp-cms-api pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"rp-cms-api\"}"
    }
   ]
  },
  {
   "title": "rp-cms-api ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"rp-cms-api.prod.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"rp-cms-api\",destination_workload_namespace=~\"prod\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", reporter=\"destination\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "rp-cms-api Request duration by source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-cms-api.prod.svc.cluster.local\", destination_workload=~\"rp-cms-api\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "rp-cms-api CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"prod\", pod=~\"^rp-cms-api.*\", pod!~\"^rp-cms-api-v.*\"}) by (pod, container)",
     "legendFormat": "{{container}} {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"prod\", pod=~\"^rp-cms-api.*\", pod!~\"^rp-cms-api-v.*\"})\n",
     "legendFormat": "requests each"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{namespace=\"prod\", pod=~\"^rp-cms-api.*\", pod!~\"^rp-cms-api-v.*\"})\n",
     "legendFormat": "limits each"
    }
   ]
  },
  {
   "title": "rp-cms-api Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"prod\", pod=~\"^rp-cms-api.*\", pod!~\"^rp-cms-api-v.*\", container!=\"POD\", container!=\"\", image!=\"\"}) by (pod, container)",
     "legendFormat": "{{container}} {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"prod\", pod=~\"^rp-cms-api.*\", pod!~\"^rp-cms-api-v.*\"})\n",
     "legendFormat": "requests each"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"prod\", pod=~\"^rp-cms-api.*\", pod!~\"^rp-cms-api-v.*\"})\n",
     "legendFormat": "limits each"
    }
   ]
  },
  {
   "title": "rp-vp pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"rp-vp\"}"
    }
   ]
  },
  {
   "title": "rp-vp ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"rp-vp.prod.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"rp-vp\",destination_workload_namespace=~\"prod\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", reporter=\"destination\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "rp-vp Request duration by source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-vp.prod.svc.cluster.local\", destination_workload=~\"rp-vp\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "rp-vp CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"prod\", pod=~\"^rp-vp.*\"}) by (pod, container)",
     "legendFormat": "{{container}} {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"prod\", pod=~\"^rp-vp.*\"})\n",
     "legendFormat": "requests each"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{namespace=\"prod\", pod=~\"^rp-vp.*\"})\n",
     "legendFormat": "limits each"
    }
   ]
  },
  {
   "title": "rp-vp Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"prod\", pod=~\"^rp-vp.*\", container!=\"POD\", container!=\"\", image!=\"\"}) by (pod, container)",
     "legendFormat": "{{container}} {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"prod\", pod=~\"^rp-vp.*\"})\n",
     "legendFormat": "requests each"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"prod\", pod=~\"^rp-vp.*\"})\n",
     "legendFormat": "limits each"
    }
   ]
  },
  {
   "title": "rp-rpany-api-go pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"rp-rpany-api-go\"}"
    }
   ]
  },
  {
   "title": "rp-rpany-api-go ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\",reporter=\"destination\",destination_workload=~\"rp-rpany-api-go\",destination_workload_namespace=~\"prod\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", reporter=\"destination\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[5m])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "rp-rpany-api-go Request duration by source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    },
    {
     "expr": "(histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P50"
    },
    {
     "expr": "(histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P90"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P95"
    },
    {
     "expr": "(histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le)) / 1000) or histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\", connection_security_policy!=\"mutual_tls\", destination_service=~\"rp-rpany-api-go.prod.svc.cluster.local\", destination_workload=~\"rp-rpany-api-go\", destination_workload_namespace=~\"prod\"}[1m])) by (destination_workload, destination_workload_namespace, le))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} P99"
    }
   ]
  },
  {
   "title": "rp-rpany-api-go CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"prod\", pod=~\"^rp-rpany-api-go.*\"}) by (pod, container)",
     "legendFormat": "{{container}} {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"prod\", pod=~\"^rp-rpany-api-go.*\"})\n",
     "legendFormat": "requests each"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits_cpu_cores{namespace=\"prod\", pod=~\"^rp-rpany-api-go.*\"})\n",
     "legendFormat": "limits each"
    }
   ]
  },
  {
   "title": "rp-rpany-api-go Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"prod\", pod=~\"^rp-rpany-api-go.*\", container!=\"POD\", container!=\"\", image!=\"\"}) by (pod, container)",
     "legendFormat": "{{container}} {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"prod\", pod=~\"^rp-rpany-api-go.*\"})\n",
     "legendFormat": "requests each"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"prod\", pod=~\"^rp-rpany-api-go.*\"})\n",
     "legendFormat": "limits each"
    }
   ]
  }
 ]
}